# Test Qibolab Rust API
name: Rust API

on:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Prepare virtual environment
        run: |
          pip install .
      - uses: dtolnay/rust-toolchain@stable
      - name: Check and lint
        working-directory: crate
        run: |
          cargo check
          cargo clippy --all-targets
      - name: Build & run example
        working-directory: crate
        run: |
          cargo run --example example
